<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Group 2 Rodney Hawkins, Mary Romero Oxa, Tejaskumar Patel">

<title>Mini Project Informs Data Challenge</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="Mini_Project_Informs_Student_files/libs/clipboard/clipboard.min.js"></script>
<script src="Mini_Project_Informs_Student_files/libs/quarto-html/quarto.js"></script>
<script src="Mini_Project_Informs_Student_files/libs/quarto-html/popper.min.js"></script>
<script src="Mini_Project_Informs_Student_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Mini_Project_Informs_Student_files/libs/quarto-html/anchor.min.js"></script>
<link href="Mini_Project_Informs_Student_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Mini_Project_Informs_Student_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Mini_Project_Informs_Student_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Mini_Project_Informs_Student_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Mini_Project_Informs_Student_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Mini Project Informs Data Challenge</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Group 2 Rodney Hawkins, Mary Romero Oxa, Tejaskumar Patel </p>
          </div>
  </div>
    
  
    
  </div>
  

</header>

<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">Introduction</h2>
<p>This project is based on the dataset provided for the <a href="https://connect.informs.org/HigherLogic/System/DownloadDocumentFile.ashx?DocumentFileKey=cc03a951-a39a-467a-be4a-0189b203c4ca">INFORMS 2023 Data Challenge</a>. INFORMS teamed up with Blue Summit Supplies, an online retailer based in Alabama, to tackle real-world challenges in setting the right prices for their products. The eCommerce market is fast-paced, with prices changing constantly. Quick and smart pricing decisions are essential for staying competitive and profitable. The Informs data challenge aims to use the company’s actual sales data to explore how pricing impacts profits, with the goal of helping the company make better, faster pricing decisions. This projects takes a different route. As a team, your task is to understand the dataset and prepare it for further analyses.</p>
<ul>
<li><p><strong>Programming Language</strong>: R</p></li>
<li><p><strong>Deliverables</strong>: Quarto Document (.qmd) and HTML Knitted Document</p></li>
<li><p><strong>Libraries</strong>: Any libraries you deem necessary</p></li>
<li><p>There are 8 tasks, each is worth 12.5 points.</p></li>
</ul>
<section id="data-set-description" class="level4">
<h4 class="anchored" data-anchor-id="data-set-description">Data Set Description</h4>
<ul>
<li><p><code>sku</code>: This is the product ID, a unique identifier for each product.</p></li>
<li><p><code>salesdate</code>: This represents the date on which a particular product was sold.</p></li>
<li><p><code>price</code>: This is the price at which the product was sold on a given day.</p></li>
<li><p><code>unitsordered</code>: This variable shows the number of units of a product ordered on a particular day.</p></li>
<li><p><code>sales</code>: This represents the total revenue generated from the sale of a product on a given day (it is calculated as the product`s price times the number of units ordered).</p></li>
<li><p><code>cogs</code>: This stands for “Cost of Goods Sold”, which is the direct cost incurred by the company to produce or purchase the product.</p></li>
<li><p><code>fba</code>: This is the eCommerce fee associated with selling the product. It includes the costs of storage, packing, and shipping handled by Amazon.</p></li>
<li><p><code>reffee</code>: This is the eCommerce platform fee associated with selling the product (15% of sales).</p></li>
<li><p><code>adspend</code>: This represents the advertisement cost associated with the product.</p></li>
<li><p><code>profit</code>: This is the profit obtained from selling the product, calculated as sales minus the sum of cogs, fba, reffee, and adspend (profit = sales - cogs - fba - reffee - adspend).</p></li>
<li><p><code>comp_x_price</code>: This represents the price of a similar product sold by a competitor. Up to 5 competitors` price data are available for each product (67 items have O competitors, 65 items have 1 competitor, 56 items have 2 competitors, 28 items have 3 competitors, 9 items have 4 competitors, 2 items have 5 competitors).</p></li>
<li><p><code>comp_data_min_price</code>: This is the minimum price among all competitors for a similar product.</p></li>
<li><p><code>comp_data_max_price</code>: This is the maximum price among all competitors for a similar product.</p></li>
<li><p><code>managed_fba_stock_level</code>: This represents the available quantity of the product in stock.</p></li>
<li><p><code>min_price</code>: This is the minimum allowable selling price for the product</p></li>
<li><p><code>max_price</code>: This is the maximum allowable selling price for the product.</p></li>
</ul>
</section>
<section id="read-the-data-in-r" class="level4">
<h4 class="anchored" data-anchor-id="read-the-data-in-r">Read the data in R</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>informs <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"~/Downloads/csv/2023_INFORMS_BSS_Data_Challenge_Dataset_1.csv"</span>, <span class="at">header=</span><span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="task-1" class="level4">
<h4 class="anchored" data-anchor-id="task-1">TASK 1:</h4>
<p>In this task, you will be ensuring that all variables in the dataset <code>informs</code> are of the correct type. This is a crucial step in any data analysis project, as incorrect variable types can lead to misleading analyses and results.</p>
<section id="details" class="level5">
<h5 class="anchored" data-anchor-id="details">Details:</h5>
<ul>
<li><p>Declare categorical variables as factors.</p></li>
<li><p>Convert the date variable to a date format.</p></li>
<li><p>Ensure that numerical variables are set as numerical data types.</p></li>
<li><p>Your R object, <code>informs</code> , should have <code>122801</code> rows and <code>20</code> columns.</p></li>
<li><p>Print the data structure below with <code>str(informs)</code> function.</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>informs<span class="sc">$</span>sku <span class="ot">&lt;-</span> <span class="fu">factor</span>(informs<span class="sc">$</span>sku)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>informs<span class="sc">$</span>salesdate <span class="ot">&lt;-</span> <span class="fu">as.Date</span>(informs<span class="sc">$</span>salesdate)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(informs)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   122801 obs. of  20 variables:
 $ sku                    : Factor w/ 227 levels "Binder Dividers SKU 1",..: 61 61 61 61 61 61 61 61 61 61 ...
 $ salesdate              : Date, format: "2022-01-01" "2022-01-02" ...
 $ price                  : num  29.5 30 29.7 29.8 29.8 ...
 $ unitsordered           : int  19 13 84 78 83 61 66 18 20 70 ...
 $ sales                  : num  560 390 2494 2324 2473 ...
 $ cogs                   : num  236 161 1042 968 1030 ...
 $ fba                    : num  156 107 690 641 682 501 543 148 164 575 ...
 $ reffee                 : num  84 58 374 349 371 273 290 81 90 314 ...
 $ adspend                : num  0 0 0 0 0 0 0 0 0 0 ...
 $ profit                 : num  84 64 388 366 390 292 281 88 98 334 ...
 $ comp_1_price           : num  28.5 28.5 28.5 28.5 28.5 ...
 $ comp_2_price           : num  28 28 28 28 28 ...
 $ comp_3_price           : num  31 31 31 31 31 ...
 $ comp_4_price           : num  NA NA NA NA NA NA NA NA NA NA ...
 $ comp_5_price           : num  NA NA NA NA NA NA NA NA NA NA ...
 $ comp_data_min_price    : num  28 28 28 28 28 ...
 $ comp_data_max_price    : num  31 31 31 31 31 ...
 $ managed_fba_stock_level: int  NA NA NA NA NA NA NA NA NA NA ...
 $ min_price              : num  28 28 28 28 28 ...
 $ max_price              : num  35 35 35 35 35 ...</code></pre>
</div>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(informs)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>              sku  salesdate price unitsordered sales cogs fba reffee adspend
1 Envelopes SKU 4 2022-01-01 29.49           19   560  236 156     84       0
2 Envelopes SKU 4 2022-01-02 29.99           13   390  161 107     58       0
3 Envelopes SKU 4 2022-01-03 29.69           84  2494 1042 690    374       0
4 Envelopes SKU 4 2022-01-04 29.79           78  2324  968 641    349       0
5 Envelopes SKU 4 2022-01-05 29.79           83  2473 1030 682    371       0
6 Envelopes SKU 4 2022-01-06 29.89           61  1823  757 501    273       0
  profit comp_1_price comp_2_price comp_3_price comp_4_price comp_5_price
1     84        28.49        27.97        30.99           NA           NA
2     64        28.49        27.97        30.99           NA           NA
3    388        28.49        27.97        30.99           NA           NA
4    366        28.49        27.97        30.99           NA           NA
5    390        28.49        27.97        30.99           NA           NA
6    292        28.49        27.97        30.99           NA           NA
  comp_data_min_price comp_data_max_price managed_fba_stock_level min_price
1               27.97               30.99                      NA     27.99
2               27.97               30.99                      NA     27.99
3               27.97               30.99                      NA     27.99
4               27.97               30.99                      NA     27.99
5               27.97               30.99                      NA     27.99
6               27.97               30.99                      NA     27.99
  max_price
1     34.99
2     34.99
3     34.99
4     34.99
5     34.99
6     34.99</code></pre>
</div>
</div>
</section>
</section>
<section id="task-2" class="level4">
<h4 class="anchored" data-anchor-id="task-2">TASK 2:</h4>
<p>In this task, you are required to calculate the percentage of missing values for each variable in the <code>informs</code> dataset and display the results in a table. Understanding the extent of missing data is a crucial step in data analysis, as it can significantly impact the results.</p>
<section id="details-1" class="level5">
<h5 class="anchored" data-anchor-id="details-1">Details:</h5>
<ul>
<li><p>Your printed table should display the variable name, <code>variable</code> in the first column and the percentage of missing values, called <code>Percent_Missing</code>, in the second column.</p></li>
<li><p>The table should be sorted in descending order based on the percentage of missing-ness (<code>Percent_Missing</code>). If two variables have the same percentage of missing-ness, then they should be sorted by their variable names (<code>variable</code>) in ascending alphabetical order.</p></li>
<li><p>Your code should print the table below</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>missing_data <span class="ot">&lt;-</span> <span class="cf">function</span>(informs){</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>  missing_percentage <span class="ot">&lt;-</span> <span class="fu">sapply</span>(informs, <span class="cf">function</span>(x) <span class="fu">sum</span>(<span class="fu">is.na</span>(x))<span class="sc">/</span><span class="fu">length</span>(x)<span class="sc">*</span><span class="dv">100</span>)</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>  missing_df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">variable =</span> <span class="fu">names</span>(missing_percentage), <span class="at">Percent_Missing =</span> missing_percentage)</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>  missing_df <span class="ot">&lt;-</span> missing_df[<span class="fu">order</span>(<span class="sc">-</span>missing_df<span class="sc">$</span>Percent_Missing, missing_df<span class="sc">$</span>variable), ]</span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">print</span>(missing_df)</span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a><span class="fu">missing_data</span>(informs)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                                       variable Percent_Missing
comp_5_price                       comp_5_price        98.55376
comp_4_price                       comp_4_price        94.08718
comp_3_price                       comp_3_price        83.09541
comp_2_price                       comp_2_price        60.53371
comp_1_price                       comp_1_price        35.88652
comp_data_max_price         comp_data_max_price        30.57223
comp_data_min_price         comp_data_min_price        30.57223
managed_fba_stock_level managed_fba_stock_level        19.70831
adspend                                 adspend         0.00000
cogs                                       cogs         0.00000
fba                                         fba         0.00000
max_price                             max_price         0.00000
min_price                             min_price         0.00000
price                                     price         0.00000
profit                                   profit         0.00000
reffee                                   reffee         0.00000
sales                                     sales         0.00000
salesdate                             salesdate         0.00000
sku                                         sku         0.00000
unitsordered                       unitsordered         0.00000</code></pre>
</div>
</div>
</section>
</section>
<section id="task-3" class="level4">
<h4 class="anchored" data-anchor-id="task-3">TASK 3:</h4>
<p>In this task, you are required to create a new column in the <strong><code>informs</code></strong> dataset called <strong><code>number_competitors</code></strong>. This column should contain the total number of competitors. In other words, it contains the total number of non-missing values for the competitor price variables: <strong><code>comp_1_price</code></strong>, <strong><code>comp_2_price</code></strong>, <strong><code>comp_3_price</code></strong>, <strong><code>comp_4_price</code></strong>, and <strong><code>comp_5_price</code></strong>.</p>
<section id="details-2" class="level5">
<h5 class="anchored" data-anchor-id="details-2">Details:</h5>
<ul>
<li><p>The <strong><code>number_competitors</code></strong> column will have a value of <code>0</code> if there are no competitor data available for that particular row.</p></li>
<li><p>If data from only three competitors is present in a given row, then <strong><code>number_competitors</code></strong> will have a value of 3.</p></li>
<li><p>After completing this task, your <strong><code>informs</code></strong> data frame should consist of 122,801 rows and 21 columns</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>informs<span class="sc">$</span>number_competitors <span class="ot">&lt;-</span> <span class="fu">rowSums</span>(<span class="sc">!</span><span class="fu">is.na</span>(informs[, <span class="fu">c</span>(<span class="st">'comp_1_price'</span>, <span class="st">'comp_2_price'</span>, <span class="st">'comp_3_price'</span>, <span class="st">'comp_4_price'</span>, <span class="st">'comp_5_price'</span>)]))</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(informs)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   122801 obs. of  21 variables:
 $ sku                    : Factor w/ 227 levels "Binder Dividers SKU 1",..: 61 61 61 61 61 61 61 61 61 61 ...
 $ salesdate              : Date, format: "2022-01-01" "2022-01-02" ...
 $ price                  : num  29.5 30 29.7 29.8 29.8 ...
 $ unitsordered           : int  19 13 84 78 83 61 66 18 20 70 ...
 $ sales                  : num  560 390 2494 2324 2473 ...
 $ cogs                   : num  236 161 1042 968 1030 ...
 $ fba                    : num  156 107 690 641 682 501 543 148 164 575 ...
 $ reffee                 : num  84 58 374 349 371 273 290 81 90 314 ...
 $ adspend                : num  0 0 0 0 0 0 0 0 0 0 ...
 $ profit                 : num  84 64 388 366 390 292 281 88 98 334 ...
 $ comp_1_price           : num  28.5 28.5 28.5 28.5 28.5 ...
 $ comp_2_price           : num  28 28 28 28 28 ...
 $ comp_3_price           : num  31 31 31 31 31 ...
 $ comp_4_price           : num  NA NA NA NA NA NA NA NA NA NA ...
 $ comp_5_price           : num  NA NA NA NA NA NA NA NA NA NA ...
 $ comp_data_min_price    : num  28 28 28 28 28 ...
 $ comp_data_max_price    : num  31 31 31 31 31 ...
 $ managed_fba_stock_level: int  NA NA NA NA NA NA NA NA NA NA ...
 $ min_price              : num  28 28 28 28 28 ...
 $ max_price              : num  35 35 35 35 35 ...
 $ number_competitors     : num  3 3 3 3 3 3 3 3 3 3 ...</code></pre>
</div>
</div>
</section>
</section>
<section id="task-4" class="level4">
<h4 class="anchored" data-anchor-id="task-4">TASK 4:</h4>
<ul>
<li><p>In this task, you are required to create two new columns in the informs dataset called <strong><code>median_competitor_price</code></strong> and <strong><code>price_differences</code></strong>.</p></li>
<li><p>This first column,<strong><code>median_competitor_price</code></strong> , should contain the median price among competitors. In other words, it contains the median of non-missing values for the competitor price variables: <strong><code>comp_1_price</code></strong>, <strong><code>comp_2_price</code></strong>, <strong><code>comp_3_price</code></strong>, <strong><code>comp_4_price</code></strong>, and <strong><code>comp_5_price</code></strong>. The <strong><code>median_competitor_price</code></strong> column will have a value of <strong><code>NA</code></strong> if there are no competitor data available for that particular row.</p></li>
<li><p>The second column, <strong><code>price_differences</code></strong> should represent the difference between the company’s price (<code>price</code>) and the median competitor price, <strong><code>median_competitor_price</code></strong> , for each transaction (row). If there are no competitor data available for that particular row, set <strong><code>price_differences</code></strong> to <code>NA</code>.</p></li>
<li><p>After completing this task, your informs data frame should consist of 122,801 rows and 23 columns.<br>
</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>informs<span class="sc">$</span>median_competitor_price <span class="ot">&lt;-</span> <span class="fu">apply</span>(informs[, <span class="fu">c</span>(<span class="st">'comp_1_price'</span>, <span class="st">'comp_2_price'</span>, <span class="st">'comp_3_price'</span>, <span class="st">'comp_4_price'</span>, <span class="st">'comp_5_price'</span>)], <span class="dv">1</span>, median, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>informs<span class="sc">$</span>price_differences <span class="ot">&lt;-</span> informs<span class="sc">$</span>price <span class="sc">-</span> informs<span class="sc">$</span>median_competitor_price</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>informs<span class="sc">$</span>price_differences[<span class="fu">is.na</span>(informs<span class="sc">$</span>median_competitor_price)] <span class="ot">&lt;-</span> <span class="cn">NA</span></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(informs)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   122801 obs. of  23 variables:
 $ sku                    : Factor w/ 227 levels "Binder Dividers SKU 1",..: 61 61 61 61 61 61 61 61 61 61 ...
 $ salesdate              : Date, format: "2022-01-01" "2022-01-02" ...
 $ price                  : num  29.5 30 29.7 29.8 29.8 ...
 $ unitsordered           : int  19 13 84 78 83 61 66 18 20 70 ...
 $ sales                  : num  560 390 2494 2324 2473 ...
 $ cogs                   : num  236 161 1042 968 1030 ...
 $ fba                    : num  156 107 690 641 682 501 543 148 164 575 ...
 $ reffee                 : num  84 58 374 349 371 273 290 81 90 314 ...
 $ adspend                : num  0 0 0 0 0 0 0 0 0 0 ...
 $ profit                 : num  84 64 388 366 390 292 281 88 98 334 ...
 $ comp_1_price           : num  28.5 28.5 28.5 28.5 28.5 ...
 $ comp_2_price           : num  28 28 28 28 28 ...
 $ comp_3_price           : num  31 31 31 31 31 ...
 $ comp_4_price           : num  NA NA NA NA NA NA NA NA NA NA ...
 $ comp_5_price           : num  NA NA NA NA NA NA NA NA NA NA ...
 $ comp_data_min_price    : num  28 28 28 28 28 ...
 $ comp_data_max_price    : num  31 31 31 31 31 ...
 $ managed_fba_stock_level: int  NA NA NA NA NA NA NA NA NA NA ...
 $ min_price              : num  28 28 28 28 28 ...
 $ max_price              : num  35 35 35 35 35 ...
 $ number_competitors     : num  3 3 3 3 3 3 3 3 3 3 ...
 $ median_competitor_price: num  28.5 28.5 28.5 28.5 28.5 ...
 $ price_differences      : num  1 1.5 1.2 1.3 1.3 ...</code></pre>
</div>
</div>
</section>
<section id="task-5" class="level4">
<h4 class="anchored" data-anchor-id="task-5">TASK 5:</h4>
<p>In this task, your goal is to create an R object called <strong><code>average_profit_vs_competitors</code></strong> that will store the <code>sku</code> and the following two variables:</p>
<ol type="1">
<li><p>The average profit per unit for each <code>sku</code>, called <code>average_profit</code> . The <code>average_profit</code>should be calculated as <span class="math inline">\(\frac{profit}{unitsordered}\)</span>​.</p></li>
<li><p>The average number of competitors per <code>sku</code>, called <code>average_number_competitors.</code> The <code>average_number_competitors</code> for each <code>sku</code> should be calculated as <code>mean(number_competitors)</code> in R.</p></li>
</ol>
<section id="details-3" class="level5">
<h5 class="anchored" data-anchor-id="details-3"><strong>Details:</strong></h5>
<ul>
<li><p>Compute the average profit for each <code>sku</code>, labeling this new variable as <strong><code>average_profit</code></strong>.</p></li>
<li><p>Double check your calculations to make sure you do not have <strong><code>-Inf</code></strong> for <strong><code>average_profit</code></strong> values. The issue of <strong><code>-Inf</code></strong> most likely arises when <strong><code>unitsordered</code></strong> is zero, as division by zero in R returns <strong><code>-Inf</code></strong>. If <strong><code>unitsordered</code></strong> is zero for a given day and <code>sku</code>, you can temporarily set it to <strong><code>NA</code></strong> to avoid <strong><code>-Inf</code></strong> in <strong><code>average_profit</code></strong> calculations.</p></li>
<li><p>Arrange these calculated average profits in descending order for easier interpretation.</p></li>
<li><p>After completing this task, your R object named <strong><code>average_profit_vs_competitors</code></strong> should have exactly 227 rows and 3 columns: <code>sku</code>, <code>average_profit</code>, and <code>average_number_competitors</code></p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute the average profit for each sku</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>informs<span class="sc">$</span>average_profit <span class="ot">&lt;-</span> informs<span class="sc">$</span>profit <span class="sc">/</span> informs<span class="sc">$</span>unitsordered</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Replace -Inf values with NA</span></span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>informs<span class="sc">$</span>average_profit[informs<span class="sc">$</span>unitsordered <span class="sc">==</span> <span class="dv">0</span>] <span class="ot">&lt;-</span> <span class="cn">NA</span></span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Arrange the average profits in descending order</span></span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a>informs <span class="ot">&lt;-</span> informs[<span class="fu">order</span>(informs<span class="sc">$</span>average_profit, <span class="at">decreasing =</span> <span class="cn">TRUE</span>), ]</span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-10"><a href="#cb12-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute the average number of competitors for each sku</span></span>
<span id="cb12-11"><a href="#cb12-11" aria-hidden="true" tabindex="-1"></a>average_number_competitors <span class="ot">&lt;-</span> <span class="fu">aggregate</span>(informs<span class="sc">$</span>number_competitors, <span class="at">by =</span> <span class="fu">list</span>(informs<span class="sc">$</span>sku), mean)</span>
<span id="cb12-12"><a href="#cb12-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-13"><a href="#cb12-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Rename the columns</span></span>
<span id="cb12-14"><a href="#cb12-14" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(average_number_competitors) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"sku"</span>, <span class="st">"average_number_competitors"</span>)</span>
<span id="cb12-15"><a href="#cb12-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-16"><a href="#cb12-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Merge the two data frames by sku</span></span>
<span id="cb12-17"><a href="#cb12-17" aria-hidden="true" tabindex="-1"></a>average_profit_vs_competitors <span class="ot">&lt;-</span> <span class="fu">merge</span>(informs[, <span class="fu">c</span>(<span class="st">"sku"</span>, <span class="st">"average_profit"</span>)], average_number_competitors, <span class="at">by =</span> <span class="st">"sku"</span>)</span>
<span id="cb12-18"><a href="#cb12-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-19"><a href="#cb12-19" aria-hidden="true" tabindex="-1"></a><span class="co"># Remove duplicate rows</span></span>
<span id="cb12-20"><a href="#cb12-20" aria-hidden="true" tabindex="-1"></a>average_profit_vs_competitors <span class="ot">&lt;-</span> average_profit_vs_competitors[<span class="sc">!</span><span class="fu">duplicated</span>(average_profit_vs_competitors<span class="sc">$</span>sku), ]</span>
<span id="cb12-21"><a href="#cb12-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-22"><a href="#cb12-22" aria-hidden="true" tabindex="-1"></a><span class="co"># Check the dimensions of the object</span></span>
<span id="cb12-23"><a href="#cb12-23" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(average_profit_vs_competitors)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 227   3</code></pre>
</div>
</div>
</section>
</section>
<section id="task-6" class="level4">
<h4 class="anchored" data-anchor-id="task-6">TASK 6:</h4>
<p>In this task, you are required to create a scatter plot using the <strong><code>average_profit_vs_competitors</code></strong> dataset and interpret it. Your plot should display the relationship between <strong><code>average_profit</code></strong> and <strong><code>average_number_competitors</code></strong>, specifically for rows where <strong><code>average_profit</code></strong> is greater than zero. Additionally, include a linear regression line on the scatter plot to gauge the overall trend.</p>
<section id="details-4" class="level5">
<h5 class="anchored" data-anchor-id="details-4">Details:</h5>
<ul>
<li><p>Generate a scatter plot to display <strong><code>average_profit</code></strong> on the y-axis and <strong><code>average_number_competitors</code></strong> on the x-axis.</p></li>
<li><p>Overlay a linear regression line on the scatter plot.</p></li>
<li><p>Filter the data to include only rows where <strong><code>average_profit</code></strong> is greater than zero.</p></li>
<li><p>Label your axis</p></li>
<li><p>Interpret your findings in one short paragraph.</p></li>
</ul>
<p>Looking at the data and the line you can see a downward slope. There also seems to be 2 or 3 outliers. As you get further from 0 on the x-axis that we called “Average Number of Competitors” the data points becomes less grouped together.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>average_profit_vs_competitors <span class="ot">&lt;-</span> average_profit_vs_competitors[average_profit_vs_competitors<span class="sc">$</span>average_profit <span class="sc">&gt;</span> <span class="dv">0</span>, ]</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(average_profit_vs_competitors<span class="sc">$</span>average_number_competitors, average_profit_vs_competitors<span class="sc">$</span>average_profit, </span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">"Average Number of Competitors"</span>, </span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylab =</span> <span class="st">"Average Profit per Unit"</span>, </span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">"Relationship between Average Profit and Average Number of Competitors"</span>)</span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="fu">lm</span>(average_profit <span class="sc">~</span> average_number_competitors, <span class="at">data =</span> average_profit_vs_competitors), <span class="at">col =</span> <span class="st">"red"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Mini_Project_Informs_Student_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
</section>
<section id="task-7" class="level4">
<h4 class="anchored" data-anchor-id="task-7">TASK 7:</h4>
<ul>
<li><p>The total sales revenue of a firm is calculated as the product of the price per unit and the total quantity sold. The impact of a price increase on total sales depends on the corresponding decrease in the quantity sold. In a highly competitive market, even a small increase in price can lead to a significant drop in sales, which in turn can reduce both total sales and profits.</p>
<p>For this task, please complete the following steps:</p>
<ol type="1">
<li><p>Create a subset of the <strong><code>informs</code></strong> dataset by removing rows that have no competitors. Name this new dataset <strong><code>informs_reduced</code></strong>.</p></li>
<li><p>Calculate the correlation between <strong><code>price</code></strong> and <strong><code>profit</code></strong> for cases where <strong><code>price_differences &gt; 0</code></strong> and <strong><code>price_differences &lt;= 0</code></strong>. Print and interpret your findings.</p></li>
<li><p>Calculate the correlation between <strong><code>price</code></strong> and <strong><code>units_ordered</code></strong> for cases where <strong><code>price_differences &gt; 0</code></strong> and <strong><code>price_differences &lt;= 0</code></strong>. Print and interpret your findings.</p></li>
</ol></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a subset of the informs dataset by removing rows that have no competitors</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>informs_reduced <span class="ot">&lt;-</span> informs[<span class="sc">!</span><span class="fu">is.na</span>(informs<span class="sc">$</span>number_competitors), ]</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the correlation between price and profit for cases where price_differences &gt; 0 and price_differences &lt;= 0</span></span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>correlation_price_profit <span class="ot">&lt;-</span> <span class="fu">cor</span>(informs_reduced<span class="sc">$</span>price, informs_reduced<span class="sc">$</span>profit)</span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the correlation between price and units_ordered for cases where price_differences &gt; 0 and price_differences &lt;= 0</span></span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a>correlation_price_units_ordered <span class="ot">&lt;-</span> <span class="fu">cor</span>(informs_reduced<span class="sc">$</span>price, informs_reduced<span class="sc">$</span>unitsordered)</span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-10"><a href="#cb15-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Print and interpret your findings</span></span>
<span id="cb15-11"><a href="#cb15-11" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"The correlation between price and profit for cases where price_differences &gt; 0 and price_differences &lt;= 0 is"</span>, correlation_price_profit, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>The correlation between price and profit for cases where price_differences &gt; 0 and price_differences &lt;= 0 is 0.2512328 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"The correlation between price and units_ordered for cases where price_differences &gt; 0 and price_differences &lt;= 0 is"</span>, correlation_price_units_ordered, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>The correlation between price and units_ordered for cases where price_differences &gt; 0 and price_differences &lt;= 0 is 0.149946 </code></pre>
</div>
</div>
</section>
<section id="task-8" class="level4">
<h4 class="anchored" data-anchor-id="task-8">TASK 8:</h4>
<p>Based on your insights from Task 7, earlier tasks, or your own analyses, provide a pricing recommendation to help the company’s to increase their profitability. Keep your response concise. You may include a graph or analysis to substantiate your recommendation. Summarize your suggestion and rationale in a brief paragraph.</p>
<p>Looking at the data and taking into account, the correlations between price and profit, along with price and unit ordered. It does not seem to be very strong correlation. Knowing this my pricing recommendation would be to incrementally and gradually increase prices, but not to drastically increase prices. Since there does not seem to be, much correlation between those variables there is probably a sweet spot of what customers will buy depending on the price.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co">#install.packages("corrplot")</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(corrplot)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>corrplot 0.92 loaded</code></pre>
</div>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> informs_reduced</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>cor_matrix <span class="ot">&lt;-</span> <span class="fu">cor</span>(df[,<span class="fu">c</span>(<span class="st">"price"</span>, <span class="st">"profit"</span>, <span class="st">"unitsordered"</span>, <span class="st">"max_price"</span>, <span class="st">"min_price"</span>, <span class="st">"reffee"</span>, <span class="st">"sales"</span>)])</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a><span class="fu">corrplot</span>(cor_matrix, <span class="at">method=</span><span class="st">"color"</span>, <span class="at">type=</span><span class="st">"upper"</span>, <span class="at">diag=</span><span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Mini_Project_Informs_Student_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>